trigger:
  branches:
    include:
      - main

pool:
  name: Test_pool   # <-- your self-hosted agent pool

steps:
- checkout: self
  clean: true

- script: |
    docker --version
    id
  displayName: 'Check docker and user'

- script: |
    docker build -t devopstest:$(Build.BuildId) .
  displayName: 'Build Docker image'

- script: |
    # stop any previous run (ignore if not exists)
    docker rm -f devopstest 2>/dev/null || true
    docker run -d --name devopstest -p 8080:80 devopstest:$(Build.BuildId)
    echo "Container started. Try: http://<AGENT_PUBLIC_IP>:8080"
  displayName: 'Run container'

- script: |
    sleep 2
    if command -v curl >/dev/null 2>&1; then
      echo "HTTP check on agent (localhost:8080):"
      curl -sSf http://localhost:8080 | head -n 5
    else
      echo "curl not found, skipping HTTP check"
    fi
  displayName: 'Health check (curl localhost:8080)'

- script: |
    echo "Containers:"
    docker ps
    echo "Recent container logs:"
    docker logs --tail 50 devopstest || true
  displayName: 'Show container status & logs'
